server:
  port: 9091
  
spring:
  application:
    name: WELCOME-APT
    
  boot:
    admin:
      client:
        url: http://localhost:1199/
        

management:
  endpoints:
    web:
      exposure:
        include: '*'
                
        