
spring:
  application:
    name: GREET-API
  boot:
    admin:
      client:
          url: http://localhost:1199/
            

management:
  endpoints:
    web:
      exposure:
        include: '*'
           