server:
  port: 2001
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mantookhan@123
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
  jpa:
    show-sql: true  