spring:
  application:
    name: 30-API-Gate-ways
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://28-WELCOME-SERVICE
        predicates:
        - Path=/welcome 
      - id: api-2
        uri: lb://29-GREET-SERVICE
        predicates:
        - Path=/greet
server:
  port: 3333 

 